#![allow(warnings)]

mod args;
#[cfg(feature = "generic-derive")]
mod bounds;
mod enum_simple;
mod filter;
mod from_tuple;
mod ordering;
mod enum_union;
mod from_instance;
mod generics;
mod instance;
mod json_deserialize;
mod prelude;
mod schema;
mod serde_impl;
mod r#struct;
mod type_name;

use crate::enum_simple::implement_for_simple_enum;
use crate::enum_union::implement_for_tagged_enum;
use crate::prelude::*;
use crate::r#struct::implement_for_struct;
use tracing::trace;

/// Determine whether an enum is a simple enum or a tagged union, and delegate to the appropriate implementation
fn implement_for_enum(
    input: &DeriveInput,
    data_enum: &DataEnum,
    opts: &TDBModelOpts,
) -> proc_macro2::TokenStream {
    // Check if all variants are simple (unit variants without data)
    let all_variants_are_simple = data_enum
        .variants
        .iter()
        .all(|variant| matches!(variant.fields, Fields::Unit));

    if all_variants_are_simple {
        // This is a simple enum, use the simple enum implementation
        implement_for_simple_enum(input, data_enum, opts)
    } else {
        // This is a tagged union enum, use the tagged union implementation
        implement_for_tagged_enum(input, data_enum, opts)
    }
}

/// Automatically derives the `ToTDBSchema` trait for a struct or enum.
///
/// This macro generates TerminusDB schema definitions from Rust data structures.
/// It can be used on both structs (maps to TerminusDB Classes) and enums (maps to TerminusDB TaggedUnions).
///
/// # Struct Attributes
///
/// The following attributes can be used on structs or enums:
///
/// - `#[tdb(class_name = "CustomName")]` - Specify a custom class name (defaults to struct/enum name).
/// - `#[tdb(base = "http://example.com/")]` - Specify a base URI.
/// - `#[tdb(key = "value_hash")]` - Key strategy (one of "random", "value_hash", "hash", "lexical").
/// - `#[tdb(key_fields = "field1,field2")]` - Comma-separated list of fields for "lexical" or "hash" keys.
/// - `#[tdb(id_field = "id")]` - Field to use as document ID. Must be `Option<T>` for non-random keys.
/// - `#[tdb(subdocument = true)]` - Mark as a subdocument.
/// - `#[tdb(abstract_class = true)]` - Mark as an abstract class.
/// - `#[tdb(unfoldable = false)]` - Control whether the class is unfoldable.
/// - `#[tdb(inherits = "BaseClass")]` - Specify inheritance.
/// - `#[tdb(doc = "Class documentation")]` - Provide documentation.
/// - `#[tdb(rename_all = "lowercase")]` - Rename all enum variants (for enums only). Supported values:
///   "lowercase", "UPPERCASE", "PascalCase", "camelCase", "snake_case", "SCREAMING_SNAKE_CASE", "kebab-case".
///
/// # Field Attributes
///
/// The following attributes can be used on struct fields:
///
/// - `#[tdb(name = "customName")]` - Custom property name (defaults to field name).
/// - `#[tdb(class = "xsd:string")]` - Specify a custom class for this field.
/// - `#[tdb(doc = "Property documentation")]` - Provide documentation.
///
/// # Examples
///
/// ## Basic Struct Example
///
/// ```rust
/// use terminusdb_schema_derive::TerminusDBModel;
/// use terminusdb_schema::ToTDBSchema;
/// use terminusdb_schema::ToTDBInstance;
/// use terminusdb_schema::FromTDBInstance;
///
/// #[derive(TerminusDBModel)]
/// struct Person {
///     id: String,
///     name: String,
///     age: i32,
///     email: Option<String>,
/// }
///
/// // Now you can use Person::to_schema() to get the TerminusDB schema
/// // and Person::from_instance() to deserialize from TerminusDB instances
/// ```
///
/// ## Lexical Key Example
///
/// ```ignore
/// use terminusdb_schema_derive::TerminusDBModel;
/// use terminusdb_schema::ToTDBSchema;
///
/// #[derive(TerminusDBModel)]
/// #[tdb(key = "lexical", key_fields = "first_name,last_name")]
/// struct PersonWithLexicalKey {
///     first_name: String,
///     last_name: String,
///     age: i32,
/// }
///
/// // This will generate a Lexical key using first_name and last_name fields
/// // The resulting URI will be like: PersonWithLexicalKey_John_Doe
/// ```
///
/// ## ID Field Example
///
/// When using deterministic key strategies (lexical, hash, value_hash), the id_field
/// must be Option<T> because the ID is generated by TerminusDB:
///
/// ```ignore
/// use terminusdb_schema_derive::TerminusDBModel;
///
/// #[derive(TerminusDBModel)]
/// #[tdb(key = "lexical", key_fields = "email", id_field = "id")]
/// struct User {
///     id: Option<String>,  // Must be Option for non-random keys
///     email: String,
///     name: String,
/// }
///
/// // For random keys, id_field can be non-Option:
/// #[derive(TerminusDBModel)]
/// #[tdb(key = "random", id_field = "id")]
/// struct Document {
///     id: String,  // Can be String for random keys
///     content: String,
/// }
/// ```
///
/// ## Enum Example (TaggedUnion)
///
/// ```rust
/// use terminusdb_schema_derive::TerminusDBModel;
/// use terminusdb_schema::ToTDBSchema;
/// use terminusdb_schema::ToTDBInstance;
/// use terminusdb_schema::FromTDBInstance;
///
/// #[derive(TerminusDBModel)]
/// #[tdb(class_name = "ContentType")]
/// enum Content {
///     TextContent,
///     ImageContent,
///     VideoContent,
/// }
///
/// // Now you can use Content::to_schema() to get the TerminusDB schema
/// // and Content::from_instance() to deserialize from TerminusDB instances
/// ```
#[proc_macro_derive(TerminusDBModel, attributes(tdb))]
pub fn derive_terminusdb_model(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);

    // Add debug message to help diagnose
    // trace!("Processing TerminusDBModel derive for: {}", input.ident);

    // Parse the attributes using darling
    let mut opts = match TDBModelOpts::from_derive_input(&input) {
        Result::Ok(opts) => opts,
        Err(err) => {
            // Convert darling::Error to a compile error
            let error_string = err.to_string();
            // trace!("Error parsing attributes: {}", error_string);
            return syn::Error::new(proc_macro2::Span::call_site(), error_string)
                .to_compile_error()
                .into();
        }
    };

    // Store the original input for doc extraction
    opts.original_input = Some(input.clone());

    // Check for generic parameters
    if let Err(err) = generics::check_generics(&input) {
        return err.to_compile_error().into();
    }

    // Generate implementation based on whether this is a struct or enum
    let expanded = match &input.data {
        Data::Struct(data_struct) => {
            trace!("Implementing for struct: {}", input.ident);
            implement_for_struct(&input, data_struct, &opts)
        }
        Data::Enum(data_enum) => {
            trace!("Implementing for enum: {}", input.ident);
            implement_for_enum(&input, data_enum, &opts)
        }
        Data::Union(_) => {
            trace!("Error: Unions not supported for {}", input.ident);
            return syn::Error::new(
                proc_macro2::Span::call_site(),
                "TerminusDBModel derive macro does not support unions",
            )
            .to_compile_error()
            .into();
        }
    };

    // Generate InstanceFromJson implementation separately
    // Need to clone `input` as `derive_instance_from_json_impl` might consume it
    let instance_from_json_impl =
        match json_deserialize::derive_instance_from_json_impl(input.clone()) {
            Result::Ok(ts) => ts,
            Err(err) => return err.to_compile_error().into(),
        };

    // Generate FromTDBInstance implementation
    let from_instance_impl = match from_instance::derive_from_terminusdb_instance(input.clone()) {
        Result::Ok(ts) => ts,
        Err(err) => return err.to_compile_error().into(),
    };

    // Detect if this is a simple enum (all unit variants)
    let is_simple_enum = matches!(&input.data, Data::Enum(e) if
        e.variants.iter().all(|v| matches!(v.fields, Fields::Unit)));

    // Generate serde Serialize/Deserialize implementations
    let serde_impl = serde_impl::generate_serde_impls(&input, is_simple_enum);

    // Generate the `{Model}Filter` struct + Filterable/TdbGQLFilter impls when
    // the `filters` feature is on and the model opted in via `#[tdb(filter)]`.
    let filter_impl = filter::generate_filter(&input, &opts);

    // Generate the `{Model}Ordering` struct + TdbGQLOrdering impl, gated the
    // same way as filters.
    let ordering_impl = ordering::generate_ordering(&input, &opts);

    // Combine the results
    let final_output = quote! {
        #expanded
        #instance_from_json_impl
        #from_instance_impl
        #serde_impl
        #filter_impl
        #ordering_impl
    };

    final_output.into()
}

/// Schema-only sibling of [`macro@TerminusDBModel`].
///
/// Emits **only** the schema + serialize (`ToTDBSchema` / `ToTDBInstance` /
/// `ToSchemaClass` / `Class`) impls — i.e. exactly the `#expanded` block produced
/// by [`macro@TerminusDBModel`] — and deliberately skips the deserialize direction
/// (`InstanceFromJson` / `FromTDBInstance`), the generated `serde` impls, and the
/// `{Model}Filter` / `{Model}Ordering` helpers.
///
/// Use this when a consumer supplies deserialization through a different mechanism
/// (e.g. a Relational/cache bridge) and only needs the type to serialize into a
/// TerminusDB schema/instance. It accepts the same `#[tdb(...)]` attributes as
/// [`macro@TerminusDBModel`], and additionally supports field-less unit structs
/// and tuple/newtype structs (both map to a class with no properties).
#[proc_macro_derive(TerminusDBSchema, attributes(tdb))]
pub fn derive_terminusdb_schema(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);

    // Parse the attributes using darling
    let mut opts = match TDBModelOpts::from_derive_input(&input) {
        Result::Ok(opts) => opts,
        Err(err) => {
            let error_string = err.to_string();
            return syn::Error::new(proc_macro2::Span::call_site(), error_string)
                .to_compile_error()
                .into();
        }
    };

    // Store the original input for doc extraction
    opts.original_input = Some(input.clone());

    // Check for generic parameters
    if let Err(err) = generics::check_generics(&input) {
        return err.to_compile_error().into();
    }

    // Generate ONLY the schema + serialize impls (the `#expanded` block). Unlike
    // `TerminusDBModel`, no deserialize / serde / filter / ordering code is emitted.
    let expanded = match &input.data {
        Data::Struct(data_struct) => {
            trace!("Implementing schema-only for struct: {}", input.ident);
            implement_for_struct(&input, data_struct, &opts)
        }
        Data::Enum(data_enum) => {
            trace!("Implementing schema-only for enum: {}", input.ident);
            implement_for_enum(&input, data_enum, &opts)
        }
        Data::Union(_) => {
            return syn::Error::new(
                proc_macro2::Span::call_site(),
                "TerminusDBSchema derive macro does not support unions",
            )
            .to_compile_error()
            .into();
        }
    };

    quote! {
        #expanded
    }
    .into()
}

/// Automatically derives the `FromTDBInstance` trait for a struct or enum.
///
/// **NOTE: This derive is now a no-op!**
/// The `FromTDBInstance` functionality has been integrated into `TerminusDBModel`.
/// Simply derive `TerminusDBModel` instead to get both serialization and deserialization.
///
/// This derive is kept for backward compatibility and will not generate any code.
/// It may be removed in future versions.
///
/// # Migration
///
/// Change this:
/// ```ignore
/// #[derive(TerminusDBModel, FromTDBInstance)]
/// struct Person { ... }
/// ```
///
/// To this:
/// ```ignore
/// #[derive(TerminusDBModel)]
/// struct Person { ... }
/// ```
#[proc_macro_derive(FromTDBInstance, attributes(tdb))]
pub fn derive_from_terminusdb_instance(input: TokenStream) -> TokenStream {
    // This is now a no-op - all functionality has been moved to TerminusDBModel
    quote! {
        // FromTDBInstance derive is now a no-op
        // All functionality has been integrated into TerminusDBModel
    }
    .into()
}

/// Derive tuple-based construction for a named-field struct, removing model
/// instantiation boilerplate in fixtures, examples, and tests. Generates:
///
/// 1. `From<(A, B, …)>` — build one model, converting each tuple element into its
///    field's type via [`terminusdb_schema::IntoField`].
/// 2. `IntoField<TdbLazy<Self>> for Self` — so a **reference field** (`Ref<T>`)
///    accepts either an id (`&str`) *or* a whole **nested model** value.
/// 3. `Self::from_tuples(iter)` — build a `Vec<Self>` from an array / iterator of
///    tuples (an array-of-tuples can't use `.into()` for `Vec<T>` because it would
///    collide with std's `From<[T; N]> for Vec<T>`).
///
/// ```ignore
/// #[derive(TerminusDBModel, FromTuple)]
/// #[tdb(id_field = "id")]
/// struct Book { id: EntityIDFor<Self>, title: String, author: Ref<Author> }
///
/// let one   = Book::from(("hp1", "Philosopher's Stone", "rowling"));           // ref by id
/// let nested = Book::from(("hp1", "Philosopher's Stone", Author::from((…))));  // ref by nested model
/// let many  = Book::from_tuples([("hp1", "…", "rowling"), ("hp2", "…", "rowling")]); // Vec<Book>
/// ```
#[proc_macro_derive(FromTuple)]
pub fn derive_from_tuple(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    from_tuple::derive(&input).into()
}
