//! GraphQL-related traits for TerminusDB models.
//!
//! This module provides traits that connect filter/ordering types to their models.
//! The direction is **inverted**: filters know their models, not vice versa.
//!
//! This design breaks dependency cycles by allowing filter types (generated in a
//! downstream crate) to reference model types (defined in domain crates) without
//! requiring domain crates to depend on the filter crate.

use crate::TerminusDBModel;
use serde::Serialize;

/// Marker trait for filter types that can filter a model M.
///
/// This trait is implemented on filter types (like `ProjectFilter`) to indicate
/// they can filter instances of a specific model (like `Project`).
///
/// # Example
///
/// ```ignore
/// use terminusdb_schema::{TdbGQLFilter, TerminusDBModel};
///
/// #[derive(TerminusDBModel)]
/// struct Project { name: String }
///
/// // Filter type generated by terminusdb_gql
/// #[derive(Default, Clone, Serialize)]
/// struct ProjectFilter { name: Option<StringFilter> }
///
/// // This impl connects the filter to its model
/// impl TdbGQLFilter<Project> for ProjectFilter {}
/// ```
pub trait TdbGQLFilter<M: TerminusDBModel>: Default + Clone + Serialize {}

/// Marker trait for ordering types that can order a model M.
///
/// This trait is implemented on ordering types (like `ProjectOrdering`) to indicate
/// they can order instances of a specific model (like `Project`).
///
/// # Example
///
/// ```ignore
/// use terminusdb_schema::{TdbGQLOrdering, TerminusDBModel};
///
/// #[derive(TerminusDBModel)]
/// struct Project { name: String, created_at: DateTime }
///
/// // Ordering type generated by terminusdb_gql
/// #[derive(Default, Clone, Serialize)]
/// struct ProjectOrdering { name: Option<Ordering>, created_at: Option<Ordering> }
///
/// // This impl connects the ordering to its model
/// impl TdbGQLOrdering<Project> for ProjectOrdering {}
/// ```
pub trait TdbGQLOrdering<M: TerminusDBModel>: Default + Clone + Serialize {}
